### ISSUE TITLE
Can I call a function from a personal Python Scripit in Power BI

### ISSUE THREAD

**Issue by ovdavid28** [click-here/Power-BI-and-Python#1]
In Python Script option inside Power BI, I would like to use:

from personal_script.py import function

In order to use some personal functions to do some data transformation inside Power BI

Is there a way of doing this?

I have tried:

from personal_script.py import function
I expect the output of being able to use my personal function collected in my personal Python Script, but I got:

Unable to connect
We encountered an error while trying to connect.
Details: "ADO.NET: Python script error.
Traceback (most recent call last):
  File "PythonScriptWrapper.PY", line 9, in <module>
  from personal_script import function
ImportError: No module named 'personal_script'

https://community.powerbi.com/t5/Desktop/Can-I-call-a-function-from-a-personal-Python-Scripit-in-Power-BI/m-p/813584#M391150

**Comment by click-here** [comment]
This should get you on your way: https://stackoverflow.com/questions/2349991/how-to-import-other-python-files
